// Zero-knowledge PFR (Polynomial Functional Relation) example — Appendix B, IMPR-FHFC paper.
//
// Demonstrates all five rounds of the ZK-PFR protocol using the `pfr` module:
//
//   Public key (indexer):  h(X) with h(ω^j) = Δ^j, KZG keys, domains.
//   Round 1 (prover):      R(X), C(X), m(X), S(X), row̃(X) — blinded commitments.
//                          R, C, F₁–F₅, row̃ blinded by ρ(X)·z_K(X), ρ ∈ F≤1[X].
//                          m blinded by ρ_m·z_H(X), ρ_m ∈ F.
//                          S(X) = R_S·X + ρ_S·z_K(X), R_S, ρ_S ∈ F.
//   Round 2 (prover):      F₁(X), …, F₅(X) — blinded rational-sum commitments (eq. 8).
//   Round 3 (prover):      R*(X), q(X) — degree-check and quotient (eq. 10).
//   Round 4 (prover):      h_α, R_α, C_α, row̃_α — polynomial evaluations at α.
//   Round 5 (prover):      [Q(τ)]₁ — batched KZG opening proof.
//   Verifier:              pairing check e([y]₁,[1]₂) = e([Q(τ)]₁,[τ−α]₂).
//
// Domains
//   H (size n=32, generator ω):   table domain
//   D (size 2n=64, generator Δ):  Δ² = ω
//   K (size m=128, generator κ):  index domain  (K strictly larger than H)
//
// Index pairs (r_i, c_i) with r_i < c_i and c_i ≥ t = 2:
//   128 pairs spread across a 32×32 strictly-lower-triangular region.

use ark_poly::{EvaluationDomain, Polynomial};
use pfr::{prove, verify, PfrPublicKey};

fn main() {
    let rng = &mut ark_std::test_rng();

    // -----------------------------------------------------------------------
    // Public key (indexer output)
    // h(X): h(ω^j) = Δ^j  (the table polynomial)
    // -----------------------------------------------------------------------
    let n = 32usize; // |H|: table size
    let m = 128usize; // |K|: number of index pairs  (m = 4n)
    let t = 2usize;  // strictly-lower-triangular offset (c_i ≥ r_i + t)
    let pk = PfrPublicKey::setup(n, m, t, rng);

    println!("=== Public Key ===");
    println!("n={n}, m={m}, t={t}");
    println!("h(X) degree: {}", pk.h_poly.degree());
    for j in 0..n {
        assert_eq!(
            pk.h_poly.evaluate(&pk.h_domain.element(j)),
            pk.d_domain.element(j),
            "h(ω^{j}) ≠ Δ^{j}"
        );
    }
    println!("h(ω^j) = Δ^j for all j ∈ [0,{n}) ✓");

    // -----------------------------------------------------------------------
    // Prover input: 128 index pairs (r_i, c_i) with r_i < c_i and c_i >= r_i + t
    // Generated by cycling through valid (row, col) pairs deterministically.
    // -----------------------------------------------------------------------
    let mut row_indices = Vec::with_capacity(m);
    let mut col_indices = Vec::with_capacity(m);
    {
        // Enumerate all valid strictly-lower-triangular pairs with gap ≥ t,
        // then take the first m cyclically.
        let mut pairs: Vec<(usize, usize)> = Vec::new();
        for r in 0..n {
            for c in (r + t)..n {
                pairs.push((r, c));
            }
        }
        assert!(!pairs.is_empty(), "no valid pairs");
        for i in 0..m {
            let (r, c) = pairs[i % pairs.len()];
            row_indices.push(r);
            col_indices.push(c);
        }
    }

    // -----------------------------------------------------------------------
    // Multiplicities from equation (7) with t=2.
    // -----------------------------------------------------------------------
    println!("\n=== Multiplicities (eq. 7, t={t}) ===");
    let mults = pk.compute_multiplicities(&row_indices, &col_indices);
    let total: u64 = mults.iter().sum();
    let nonzero = mults.iter().filter(|&&v| v > 0).count();
    println!("  Total = {total}  (should be 4·m = {})", 4 * m);
    println!("  Non-zero entries: {nonzero} / {n}");
    assert_eq!(total, (4 * m) as u64);

    // -----------------------------------------------------------------------
    // Prover: all 5 rounds
    // -----------------------------------------------------------------------
    println!("\n=== Prover ===");
    let (proof, public_inputs) = prove(&pk, &row_indices, &col_indices, rng);

    println!("Round 1 commitments: R, C, m, S, row̃ ✓");
    println!(
        "Round 2 commitments: F₁, F₂, F₃, F₄, F₅ ({} polys) ✓",
        proof.f_comms.len()
    );
    println!("Round 3 commitments: R*, q ✓");
    println!(
        "Round 4 evaluations: h_α={:?}, R_α={:?}, C_α={:?}, row̃_α={:?} ✓",
        proof.h_alpha, proof.r_alpha, proof.c_alpha, proof.row_alpha
    );
    println!("Round 5 commitment: Q ✓");

    // -----------------------------------------------------------------------
    // Verifier: full pairing check
    // -----------------------------------------------------------------------
    println!("\n=== Verifier ===");
    let valid = verify(&pk, &proof, &public_inputs.row_comm, &public_inputs.col_comm, &public_inputs.rowcol_comm);
    println!("Verify: {valid}");
    assert!(valid, "PFR proof verification failed");

    println!("\nPFR all 5 rounds complete ✓");
}
